version: '3'
services:
  cert-gen:
    build:
      context: ./generate_certs
      dockerfile: Dockerfile.ssl
    volumes:
      - certs:/etc/ssl/certs
      - private:/etc/ssl/private
  nginx:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - mynetwork
    volumes:
      - certs:/etc/ssl/certs
      - private:/etc/ssl/private
    depends_on:
      - cert-gen
      - app
    command: [ "/wait-for-cert-gen.sh", "nginx", "-g", "daemon off;" ]
  app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - certs:/etc/ssl/certs
      - private:/etc/ssl/private
      - db-data:/data
    depends_on:
      - cert-gen
    command:
      [
        "/wait-for-cert-gen.sh",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--ssl-keyfile",
        "/etc/ssl/private/nginx-selfsigned.key",
        "--ssl-certfile",
        "/etc/ssl/certs/nginx-selfsigned.crt"
      ]
volumes:
  certs:
  private:
  db-data:
networks:
  mynetwork:
